# Generated by Django 2.2.13 on 2020-06-08 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Parish Name')),
                ('street_address', models.CharField(max_length=256, verbose_name='Street Address')),
                ('city', models.CharField(max_length=256, verbose_name='City')),
                ('state', models.CharField(choices=[('WA', 'WA'), ('OR', 'OR')], default='WA', max_length=2, verbose_name='State')),
                ('priest', models.CharField(blank=True, max_length=256, verbose_name='Priest Name')),
                ('attendee_limit', models.IntegerField(default=10, verbose_name='Attendee Limit')),
                ('pre_register', models.IntegerField(default='6', verbose_name="Number of days ahead parishioner's may register for mass")),
                ('close_register', models.IntegerField(default='1', verbose_name='Days ahead to close registration')),
            ],
            options={
                'verbose_name_plural': 'Parishes',
            },
        ),
        migrations.CreateModel(
            name='Parishioner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Street Address')),
                ('city', models.CharField(blank=True, max_length=256, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, choices=[('WA', 'WA'), ('OR', 'OR')], default='WA', max_length=2, null=True, verbose_name='State')),
                ('zipcode', models.IntegerField(blank=True, null=True, verbose_name='Zipcode')),
                ('parish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Parish', verbose_name='Parish')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='parish',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='registration.Parishioner', verbose_name='Owner'),
        ),
        migrations.CreateModel(
            name='Mass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mass', max_length=256, verbose_name='Name')),
                ('start', models.DateTimeField(verbose_name='Start')),
                ('limit_override', models.IntegerField(blank=True, null=True, verbose_name='Override Attendee Limit')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Parish', verbose_name='Parish')),
            ],
            options={
                'verbose_name': 'Mass',
                'verbose_name_plural': 'Masses',
            },
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Mass', verbose_name='Masses')),
                ('parishioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Parishioner', verbose_name='Parishioner')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalAttendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('mass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Mass', verbose_name='Masses')),
                ('parishioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Parishioner', verbose_name='Parishioner')),
            ],
        ),
    ]
