# Generated by Django 2.2.13 on 2020-06-09 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalattendee',
            name='mass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adtl_attendees', to='registration.Mass', verbose_name='Masses'),
        ),
    ]
