# Generated by Django 2.2.13 on 2020-06-09 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200609_1108'),
        ('registration', '0003_auto_20200609_1614'),
    ]

    operations = [
    ]
