# Generated by Django 2.2.13 on 2020-06-09 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_merge_20200609_1818'),
        ('registration', '0004_auto_20200609_1758'),
    ]

    operations = [
    ]
